### ISSUE TITLE
Populate data from local Kodi inst

### ISSUE THREAD

**Issue by zarboz** [valverde-marcelo/kodi2webos#1]
From your documentation it appears that flipping the static var to false would pull images from kodi instance rather than the static image path you have defined

I also am curious if the port 9090 is for local kodi instance 

Will work on UX/UI stuff once I can iron out piping the stream from Kodi>Web OS

**Comment by valverde-marcelo** [comment]
sorry for my bad english...

#config/index.js
export const server = {
    host: '192.168.15.2', //host: 'localhost' <--- this is my local kodi instance
    ws_port: 9090, <-- this is the port number of REST API kodi
    web_port: 8080
};

export const endpoint = `ws://${server.host}:${server.ws_port}`;

export const is_static = false; <-- If "true" I use static images to perform UI tests. If "false" use images from local kodi instance

**Comment by zarboz** [comment]
Thank you, I would like to contribute. I will code in my test changes and make pull request if the features look well.
